name: CI
on: push

env:
  IMAGE_NAME: ghcr.io/zxcvve/get-a-job
  IMAGE_TAG: latest
  CONTAINER_NAME: get-a-job
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node modules
        run: npm ci
      - name: Run ESLint
        run: npm run lint

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}"
          secrets: |
            "supabase_key=${{ secrets.SUPABASE_KEY }}"

  deploy:
    needs: docker
    environment: get-a-job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            docker stop ${{env.CONTAINER_NAME}} || true && docker rm ${{env.CONTAINER_NAME}} || true
            docker rmi -f ${{env.IMAGE_NAME}} 
            docker pull ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} 
            docker run -p 1555:3000 --env-file ~/get-a-job/.env --name get-a-job ghcr.io/zxcvve/get-a-job:latest