name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node modules
        run: npm ci
      - name: Run ESLint
        run: npm run lint